version: "3.3"

services:
    web:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        image: statice:latest
        container_name: statice_web
        command: ./entrypoint.sh
        stop_grace_period: 1s
        depends_on:
            - db
        env_file:
            - ".env"
        ports:
            - "5000:5000"

    daemon:
        image: statice:latest
        container_name: statice_daemon
        command: flask daemon
        stop_grace_period: 1s
        depends_on:
            - redis
            - db
        env_file:
            - ".env"

    workers:
        build:
            context: .
            dockerfile: ./docker/workers/Dockerfile
        image: statice-workers:latest
        container_name: statice_workers
        stop_grace_period: 1s
        depends_on:
            - redis
        env_file:
            - ".env"

    redis:
        image: redis:5-alpine
        container_name: statice_redis

    db:
        image: postgres:12
        container_name: statice_db
        env_file:
            - ".env"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
