version: "3.3"

services:
    web:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        image: statice:latest
        container_name: statice_web
        command: flask run --host=0.0.0.0
        stop_grace_period: 1s
        depends_on:
            - db
        environment:
            - FLASK_ENV=development
            - FLASK_DEBUG=True
        env_file:
            - ".env"
        ports:
            - "5000:5000"
        volumes:
            - "./app:/usr/src/statice/app:ro"