version: '3'

services:
    app:
        build: .
        image: statice
        container_name: statice_app
        command: ./start.sh
        depends_on:
            - db
            - redis
        ports:
            - "5000:5000"

    worker:
        image: statice
        container_name: statice_worker
        command: flask run_worker
        depends_on:
            - db
            - redis

    daemon:
        image: statice
        container_name: statice_daemon
        command: flask run_daemon
        depends_on:
            - db
            - redis

    db:
        image: postgres:12
        container_name: statice_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:5-alpine
        container_name: statice_redis

volumes:
    postgres_data:
