version: '3'

services:
    web:
        build: .
        image: statice
        container_name: statice_web
        command: ./scripts/start_web.sh
        stop_grace_period: 1s
        depends_on:
            - db
        env_file:
            - ".env"
        ports:
            - "5000:5000"

    daemon:
        image: statice
        container_name: statice_daemon
        command: flask daemon
        stop_grace_period: 1s
        depends_on:
            - redis
            - db
        env_file:
            - ".env"

    workers:
        image: statice
        container_name: statice_workers
        command: ./scripts/start_workers.sh
        stop_grace_period: 1s
        depends_on:
            - redis
        env_file:
            - ".env"

    redis:
        image: redis:5-alpine
        container_name: statice_redis

    db:
        image: postgres:12
        container_name: statice_db
        env_file:
            - ".env"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
