version: '3'

services:
    web:
        build: .
        image: statice
        container_name: statice_web
        command: ./docker-entrypoint.sh
        depends_on:
            - db
        env_file:
            - ".env"
        ports:
            - "5000:5000"
        volumes:
            - ./app:/statice/app:ro

    daemon:
        image: statice
        container_name: statice_daemon
        command: flask daemon
        depends_on:
            - redis
            - db
        env_file:
            - ".env"
        volumes:
            - ./app:/statice/app:ro

    worker:
        image: statice
        container_name: statice_worker
        command: flask rq worker
        depends_on:
            - redis
        env_file:
            - ".env"
        volumes:
            - ./app:/statice/app:ro

    redis:
        image: redis:5-alpine
        container_name: statice_redis

    db:
        image: postgres:12
        container_name: statice_db
        env_file:
            - ".env"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
