version: '3'

services:
    web:
        build: .
        image: statice
        container_name: statice_web
        command: ./entrypoint.sh
        depends_on:
            - db
        ports:
            - "5000:5000"
        volumes:
            - ./app:/statice/app:ro

    inquisitor:
        image: statice
        container_name: statice_inquisitor
        command: flask inquisitor
        depends_on:
            - db
            - redis
        volumes:
            - ./app:/statice/app:ro

    janitor:
        image: statice
        container_name: statice_janitor
        command: flask janitor
        depends_on:
            - db
        volumes:
            - ./app:/statice/app:ro

    worker:
        image: statice
        container_name: statice_worker
        command: flask rq worker
        depends_on:
            - redis
        volumes:
            - ./app:/statice/app:ro

    db:
        image: postgres:12
        container_name: statice_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:5-alpine
        container_name: statice_redis

volumes:
    postgres_data:
